### PR TITLE
DEMO: BibTeX output with citation-js

### PR DESCRIPTION
**Pull request by zuphilip**
See also #16.

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks! Why did you label this as "DEMO"? Not ready for merging? (other than the fact that we'd need to update the on-page documentation and https://github.com/rmzelle/ref-extractor/blob/master/README.md)

It might be nicer to add an additional step after the file selection, and offer the user a drop-down menu of output formats (CSL-JSON, BibTeX, something like citation-apa, and, if Citation.js ever supports it, RIS). That way we'd only need one set of buttons.

We could also add a textarea (below or to the right) to show the extracted metadata in the selected format, which would the added benefit of giving user feedback when a different output format is selected in the dropdown menu.

(this dropdown menu would become the new step 3, and the button would move to step 4:


)

**Comment by zuphilip** [comment]
I named it DEMO because there are a lot of options how actually to do the integration. Besides from documentation etc. it should be ready to merge, maybe then as an intermediate solution. I like what you outlined with a new intermediate step to choose the format from, but I would leave this to you then to do. Also the textarea could be a nice idea.

Should I rename the PR? Can you take over from here?

**Comment by rmzelle** [comment]
Covered by #24.

> It might be nicer to add an additional step after the file selection, and offer the user a drop-down menu of output formats (CSL-JSON, BibTeX, something like citation-apa, and, if Citation.js ever supports it, RIS).

For some reason I couldn't get a rendered format like "citation-apa" to work in citation.js 0.3.4 (see https://github.com/larsgw/citation.js/issues/142). And it looks like RIS support won't happen until 0.4: https://github.com/larsgw/citation.js/issues/125.

**Comment by larsgw** [comment]
Concerning RIS, I could create an intermediary beta release, or just a bundle created from the master branch. Do you have a preference?

**Comment by rmzelle** [comment]
Could you create a beta release? That might make it easier to track down
bugs.

**Comment by larsgw** [comment]
I'll add my replies from [the other thread](https://github.com/larsgw/citation.js/issues/142) here too:

> I released the v0.4.0-3 beta with RIS support, the CDN should load up soon:
> * https://cdn.rawgit.com/larsgw/citation.js/archive/citation.js/citation-0.4.0-3.js
> * https://cdn.rawgit.com/larsgw/citation.js/archive/citation.js/citation-0.4.0-3.min.js

(The CDN links work now)

> Here's a demo on how to use the RIS output BTW: https://runkit.com/larsgw/citation.js-ris-output-demo
> 
> Basically this:
> 
> ```js
> Cite(...).get({
>   format: 'string',
>   type: 'string',
>   style: 'ris'
> })
> ```
> 
> Or, with the new API:
> 
> ```js
> Cite(...).format('ris')
> ```
> 
> Additionally, you can pass parameters:
> 
> ```js
> Cite(...).format('ris', {
>   type: 'text' // alternative: 'object' gives you an object representation
> })
> ```

**Pull request closed without merging**
